namespace EMS.API
{
    public enum ErrorCodes
    {
        INVALID_AUTHENTICATION,
        CREATED,
        NO_DATA,
        INSERTION_FAILED,
        UPDATE_FAILED,
        DELETION_FAILED,
        REGISTRATION_FAILED,
        INVALID_DATA,
        UNAUTHORIZED,
        INSERTION_SUCCESSFUL,
        FIRSTNAME_IS_REQUIRED,
        LASTNAME_IS_REQUIRED,
        EMAIL_IS_REQUIRED,
        MOBILENUMBER_IS_REQUIRED_AND_GREATER_THAN_10,
        DATE_OF_BIRTH_IS_REQUIRED,
        EMPLOYEENUMBER_IS_REQUIRED,
        JOININGDATE_IS_REQUIRED,
        DATA_IS_REQUIRED,
        LOGIN_FAILED,
        PASSWORD_IS_REQUIRED
    }
}